name: date_utils
description: A Dart library for manipulating DateTimes.
version: 0.2.0
homepage: https://github.com/apptreesoftware/date_utils

environment:
  sdk: ^3.0.0

dependencies:
  intl: ^0.18.1

dev_dependencies:
  test: ^1.16.5
